[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/b2"
  to = "/fce.html"
  status = 200

[[redirects]]
  from = "/fce-course"
  to = "/fce.html"
  status = 200

[[redirects]]
  from = "/legacy"
  to = "/index.html"
  status = 200
