(function () {
    var T = {
        intro: "\u041a\u0430\u043a \u043d\u0430 \u044d\u043a\u0437\u0430\u043c\u0435\u043d\u0435: <strong>Which person mentions the following?</strong> \u041d\u0430\u0436\u043c\u0438\u0442\u0435 \u043d\u0430 \u0438\u043c\u044f &mdash; \u043e\u0442\u043a\u0440\u043e\u0435\u0442\u0441\u044f \u0442\u0435\u043a\u0441\u0442 \u044d\u0442\u043e\u0433\u043e \u0447\u0435\u043b\u043e\u0432\u0435\u043a\u0430 \u0438 \u0442\u0435 \u0436\u0435 10 \u043f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u0439. \u041e\u0442\u043c\u0435\u0442\u044c\u0442\u0435 \u0432\u0441\u0435 \u043f\u0443\u043d\u043a\u0442\u044b, \u043a\u043e\u0442\u043e\u0440\u044b\u0435 \u043e\u043d \u0443\u043f\u043e\u043c\u0438\u043d\u0430\u0435\u0442. \u041d\u0430\u0436\u043c\u0438\u0442\u0435 \u00ab\u041f\u0440\u043e\u0432\u0435\u0440\u0438\u0442\u044c\u00bb &mdash; \u0443\u0432\u0438\u0434\u0438\u0442\u0435 \u0441\u0447\u0451\u0442 \u0438 \u0440\u0430\u0437\u0431\u043e\u0440.",
        back: "\u2190 \u041a \u0441\u043f\u0438\u0441\u043a\u0443",
        task: "\u041a\u0430\u043a\u0438\u0435 \u0438\u0437 \u0438\u0434\u0435\u0439 \u043d\u0438\u0436\u0435 \u044d\u0442\u043e\u0442 \u0447\u0435\u043b\u043e\u0432\u0435\u043a \u0443\u043f\u043e\u043c\u0438\u043d\u0430\u0435\u0442 \u0432 \u0441\u0432\u043e\u0451\u043c \u0430\u0431\u0437\u0430\u0446\u0435? \u041e\u0442\u043c\u0435\u0442\u044c\u0442\u0435 \u0432\u0441\u0435 \u043f\u043e\u0434\u0445\u043e\u0434\u044f\u0449\u0438\u0435.",
        check: "\u041f\u0440\u043e\u0432\u0435\u0440\u0438\u0442\u044c",
        retry: "\u041f\u0440\u043e\u0439\u0442\u0438 \u0441\u043d\u043e\u0432\u0430",
        tileHint: "\u0422\u0435\u043a\u0441\u0442 + \u043f\u0443\u043d\u043a\u0442\u044b 1\u201310"
    };

    function applyUiLabels() {
        var intro = document.getElementById("intro-line");
        if (intro) intro.innerHTML = T.intro;
        document.getElementById("btn-back").textContent = T.back;
        document.getElementById("btn-back2").textContent = T.back;
        document.getElementById("btn-check").textContent = T.check;
        document.getElementById("btn-retry").textContent = T.retry;
        document.getElementById("task-instruction").textContent = T.task;
    }

    var STATEMENTS = [
        { id: 1, text: "the dividends that maintaining a positive mindset pays when things look bleak" },
        { id: 2, text: "the feeling of unease that AI induces throughout the wider artistic community" },
        { id: 3, text: "the naïvety of artists in their expectations for change" },
        { id: 4, text: "the lack of resemblance of artists' contemporary working lives to past practices" },
        { id: 5, text: "the consequences of collaboration between humans and computers" },
        { id: 6, text: "the progress being made in the art world despite resistance to innovation" },
        { id: 7, text: "the need for AI to be prevented from overriding the rights of artists" },
        { id: 8, text: "the qualities brought to art by humans that cannot be replicated by computers" },
        { id: 9, text: "the implausibility of one particular situation" },
        { id: 10, text: "the virtual undetectability of artworks generated by AI" }
    ];

    var KEY = {
        1: "richard",
        2: "jack",
        3: "valentina",
        4: "richard",
        5: "jack",
        6: "valentina",
        7: "phoebe",
        8: "kiki",
        9: "richard",
        10: "phoebe"
    };

    var PEOPLE = [
        {
            id: "jack",
            letter: "A",
            name: "Jack",
            css: "tile-jack",
            text: "AI art doesn't concern me in the slightest; <em>however</em> you can understand why it causes so many artists so much discomfort. I suspect it's related to the unpredictability of where it will all end up. For my part, having been involved in a collaborative project with a gaming company recently, I can see how they go hand in hand. Over 50 artists were employed on the project, and I found it fascinating to observe firsthand the interplay of both these creative forms and how this produced an altogether better product. Artists and AI actually complement each other <em>since</em> one cannot generate output without the other's input. <em>Now that</em> I've had this experience, I'm even more convinced that there's no threat. With all that I can bring to the table, I won't be sidelined in the foreseeable future. I just wish I could get others to believe this too."
        },
        {
            id: "valentina",
            letter: "B",
            name: "Valentina",
            css: "tile-valentina",
            text: "As a graphic designer I know more than most about losing out to AI as our whole industry was turned upside down by new technology in the 80s with many people being made redundant. And this has been replicated more recently in the impact of digital on the music industry as well as print media. People are often reluctant to change, and this is no different, it's just part of the evolution of art. A recent example is graffiti artists who are always being denounced for ruining art when, in actual fact they're a long overdue breath of fresh air in a dusty old artworld. AI is on a collision course with artists for better or worse and that won't be derailed by anything human artists say or do, and nor should it be as far as I'm concerned. So the sooner artists from all walks of life stop deluding themselves that things are going to go just how they'd like them to go the better, because there's little likelihood of that."
        },
        {
            id: "phoebe",
            letter: "C",
            name: "Phoebe",
            css: "tile-phoebe",
            text: "You have to hand it to the programmers writing the algorithms and training the AI – the creations are simply incredible by any standard. Would judges in any art competition be able to single out AI generated paintings without exception? To be honest, I wonder whether anyone can reliably answer that as plenty of experts have been fooled by AI generated pieces. For me, it's tantamount to theft, though, when AI reproduces paintings or uses photos without permission. Intellectual property is fundamental to artists to ensure they don't get ripped off and can earn a decent living. Something should be done about this while the genre is still in its infancy, otherwise I imagine we can expect further issues down the line."
        },
        {
            id: "richard",
            letter: "D",
            name: "Richard",
            css: "tile-richard",
            text: "Many artists seem to fear AI, <em>whereas</em> I'm all for it! In my humble opinion, this is all about artists not wanting to move with the times. I think they are blinkered, <em>in that</em> they don't see the benefits of the technology. Gone are the days when artists could hole themselves up in a remote studio alone, painting in their same old style, and still expect to remain relevant. That kind of lifestyle is out of the question these days and artists can't risk being out of touch with what clients and society want from them, as we're expected to be diverse in what we produce. After all, artists are selling something and those who embrace technology rather than bemoaning the loss of our traditional careers will come across opportunities. They might be surprised by what it's like working with AI, however counterintuitive it may seem."
        },
        {
            id: "kiki",
            letter: "E",
            name: "Kiki",
            css: "tile-kiki",
            text: "Nowadays technology steamrolls over everything while genuinely skilled practitioners are left bringing up the rear. If it were up to me, I'd have these AI people spend time with some of our professionals <em>so as</em> to emphasise the hard graft and unique skill that is part and parcel of creativity. You've got to know your Da Vinci from your Kandinsky in terms of objectives, theories and movements as well as have a grasp of differing artistic techniques. It's about representations of the world from different perspectives, not how lifelike the computer image is because it's made from a million pixels."
        }
    ];

    var DETAILS = {
        1: "Richard (D): оптимизм, смена эпохи, «embrace technology», новые возможности.",
        2: "Jack (A): discomfort художников и unpredictability будущего.",
        3: "Valentina (B): «deluding themselves» — иллюзия, что всё пойдёт «как им хочется».",
        4: "Richard (D): ушла эпоха затворничества в студии и «того же стиля».",
        5: "Jack (A): коллаборация с gaming company, go hand in hand, altogether better product, complement each other.",
        6: "Valentina (B): эволюция искусства; graffiti как свежий воздух при сопротивлении «старому миру».",
        7: "Phoebe (C): права, разрешение, intellectual property, «something should be done».",
        8: "Kiki (E): hard graft, unique skill, теория и техника — не свести к пикселям.",
        9: "Richard (D): «surprised», counterintuitive — разрыв ожиданий и реальности.",
        10: "Phoebe (C): судьи и эксперты не отличают AI-картины безошибочно."
    };

    var LS = "reading_exam_results_v1";

    function loadStats() {
        try {
            var j = localStorage.getItem(LS);
            return j ? JSON.parse(j) : {};
        } catch (e) {
            return {};
        }
    }

    function saveStats(stats) {
        localStorage.setItem(LS, JSON.stringify(stats));
    }

    function personById(id) {
        for (var i = 0; i < PEOPLE.length; i++) {
            if (PEOPLE[i].id === id) return PEOPLE[i];
        }
        return null;
    }

    function shouldCheck(personId, stmtId) {
        return KEY[stmtId] === personId;
    }

    function showScreen(id) {
        var screens = document.querySelectorAll(".screen");
        for (var i = 0; i < screens.length; i++) {
            screens[i].classList.remove("active");
        }
        document.getElementById(id).classList.add("active");
    }

    var currentPersonId = null;

    function renderHome() {
        var grid = document.getElementById("person-grid");
        grid.innerHTML = "";
        for (var p = 0; p < PEOPLE.length; p++) {
            (function (person) {
                var btn = document.createElement("button");
                btn.type = "button";
                btn.className = "person-tile " + person.css;
                btn.innerHTML =
                    "<span class=\"letter\">" +
                    person.letter +
                    "</span><span class=\"nm\">" +
                    person.name +
                    "</span><span class=\"hint\">" +
                    T.tileHint +
                    "</span>";
                btn.addEventListener("click", function () {
                    openPerson(person.id);
                });
                grid.appendChild(btn);
            })(PEOPLE[p]);
        }

        var stats = loadStats();
        var gs = document.getElementById("global-summary");
        var parts = [];
        var totalC = 0;
        var totalT = 0;
        for (var j = 0; j < PEOPLE.length; j++) {
            var pid = PEOPLE[j].id;
            if (stats[pid]) {
                totalC += stats[pid].correct;
                totalT += stats[pid].total;
                parts.push(PEOPLE[j].name + ": " + stats[pid].correct + "/" + stats[pid].total);
            }
        }
        if (parts.length === 0) {
            gs.innerHTML = "<strong>Статистика:</strong> ещё нет проверок.";
        } else {
            gs.innerHTML =
                "<strong>Лучший результат (последняя проверка каждого):</strong><br>" +
                parts.join(" · ") +
                "<br><em>Верных отметок из " +
                totalT +
                ": " +
                totalC +
                "</em>";
        }
    }

    function openPerson(personId) {
        currentPersonId = personId;
        var p = personById(personId);
        var card = document.getElementById("reading-card");
        card.innerHTML =
            "<div class=\"reading-head\"><span class=\"L\">" +
            p.letter +
            "</span><div><strong style=\"font-size:22px\">" +
            p.name +
            "</strong></div></div><div class=\"reading-body\">" +
            p.text +
            "</div>";

        var list = document.getElementById("stmt-list");
        list.innerHTML = "";
        for (var i = 0; i < STATEMENTS.length; i++) {
            (function (s) {
                var row = document.createElement("div");
                row.className = "stmt-row";
                var cid = "st-" + s.id;
                row.innerHTML =
                    "<input type=\"checkbox\" id=\"" +
                    cid +
                    "\" data-sid=\"" +
                    s.id +
                    "\">" +
                    "<label for=\"" +
                    cid +
                    "\"><span class=\"stmt-num\">" +
                    s.id +
                    ".</span> " +
                    s.text +
                    "</label>";
                row.addEventListener("click", function (e) {
                    if (e.target.tagName !== "INPUT") {
                        var inp = row.querySelector("input");
                        inp.checked = !inp.checked;
                    }
                });
                list.appendChild(row);
            })(STATEMENTS[i]);
        }

        showScreen("screen-work");
        window.scrollTo(0, 0);
    }

    function runCheck() {
        var p = personById(currentPersonId);
        var inputs = document.querySelectorAll("#stmt-list input[type=checkbox]");
        var user = {};
        for (var i = 0; i < inputs.length; i++) {
            user[parseInt(inputs[i].dataset.sid, 10)] = inputs[i].checked;
        }

        var correct = 0;
        var rows = [];
        for (var k = 0; k < STATEMENTS.length; k++) {
            var sid = STATEMENTS[k].id;
            var need = shouldCheck(currentPersonId, sid);
            var got = !!user[sid];
            var match = need === got;
            if (match) correct++;

            var owner = KEY[sid];
            var ownerP = personById(owner);
            var explain;
            if (need) {
                explain =
                    "Нужно было <strong>отметить</strong>: пункт относится к " +
                    p.name +
                    " (" +
                    p.letter +
                    "). " +
                    DETAILS[sid];
            } else {
                explain =
                    "Нужно было <strong>не отмечать</strong>: по ключу пункт относится к " +
                    ownerP.name +
                    " (" +
                    ownerP.letter +
                    "). " +
                    DETAILS[sid];
            }
            if (!match) {
                explain += got
                    ? " <span class=\"tag-bad\">Вы отметили — ошибка.</span>"
                    : " <span class=\"tag-bad\">Вы не отметили — ошибка.</span>";
            } else {
                explain += " <span class=\"tag-ok\">Верно.</span>";
            }

            rows.push({
                sid: sid,
                stmt: STATEMENTS[k].text,
                match: match,
                need: need,
                got: got,
                explain: explain
            });
        }

        var stats = loadStats();
        stats[currentPersonId] = { correct: correct, total: 10, at: Date.now() };
        saveStats(stats);

        var heroClass = correct >= 9 ? "ok" : correct >= 6 ? "mid" : "bad";
        var tableHtml =
            "<div class=\"results-hero " +
            heroClass +
            "\"><div class=\"big\">" +
            correct +
            " / 10</div><div class=\"lbl\">верных из 10 (каждый пункт: отметить или нет)</div><p style=\"margin:12px 0 0;font-size:15px\"><strong>" +
            p.name +
            "</strong> (" +
            p.letter +
            ")</p></div>";
        tableHtml +=
            "<table class=\"result-table\"><thead><tr><th>№</th><th>Пункт</th><th>Ваш выбор</th><th>Верно?</th><th>Почему</th></tr></thead><tbody>";
        for (var r = 0; r < rows.length; r++) {
            var row = rows[r];
            tableHtml +=
                "<tr><td>" +
                row.sid +
                "</td><td>" +
                row.stmt +
                "</td><td>" +
                (row.got ? "отмечено" : "не отмечено") +
                "</td><td>" +
                (row.match ? "<span class=\"tag-ok\">да</span>" : "<span class=\"tag-bad\">нет</span>") +
                "</td><td class=\"explain\">" +
                row.explain +
                "</td></tr>";
        }
        tableHtml += "</tbody></table>";
        tableHtml +=
            "<p class=\"sub\" style=\"margin-top:0\">В полном задании каждый из 10 пунктов соответствует ровно одному человеку.</p>";

        document.getElementById("results-root").innerHTML = tableHtml;
        showScreen("screen-results");
        window.scrollTo(0, 0);
    }

    document.getElementById("btn-back").addEventListener("click", function () {
        renderHome();
        showScreen("screen-home");
    });
    document.getElementById("btn-back2").addEventListener("click", function () {
        renderHome();
        showScreen("screen-home");
    });
    document.getElementById("btn-retry").addEventListener("click", function () {
        if (currentPersonId) openPerson(currentPersonId);
    });
    document.getElementById("btn-check").addEventListener("click", runCheck);

    applyUiLabels();
    renderHome();
})();
